# SPDX-FileCopyrightText: 2026 Metacraft Labs
# SPDX-License-Identifier: Apache-2.0
name: Release

on:
  workflow_dispatch:
  push:
    branches: [release/unified-0.1.0]
    tags: ['v*']

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: metacraft-labs/metacraft-github-actions/.github/workflows/release-tools.yml@7a5126af05daa2cbb0113069eb1a4b2d7ef38dd6
    with:
      tooling-ref: 7a5126af05daa2cbb0113069eb1a4b2d7ef38dd6
      nix-shell: release
    secrets: inherit
